# Generated by Django 4.2.5 on 2023-12-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.ImageField(blank=True, null=True, upload_to='personal_information_avatar')),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('married', models.BooleanField(default=False)),
                ('have_children', models.BooleanField(default=False, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_url', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_url', models.CharField(blank=True, max_length=255, null=True)),
                ('google_url', models.CharField(blank=True, max_length=255, null=True)),
                ('pinterest_url', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('hobby', models.TextField(blank=True, null=True)),
                ('interests', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
