# Generated by Django 4.2.5 on 2023-10-14 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinformation',
            old_name='sex',
            new_name='gender',
        ),
    ]
