# Generated by Django 4.2.5 on 2023-11-17 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_sellerreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerReview',
        ),
    ]
