# Generated by Django 4.2.5 on 2023-11-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_orderreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreview',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
