# Generated by Django 4.2.5 on 2023-11-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_orderreview_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderReview',
        ),
    ]
