# Generated by Django 4.2.5 on 2023-11-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_delete_orderreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='married',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
