# Generated by Django 4.2.5 on 2023-11-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_personalinformation_married'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalInformation',
        ),
    ]
