# Generated by Django 4.2.5 on 2023-10-10 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='category_id',
            new_name='category',
        ),
    ]
