# Generated by Django 4.2.5 on 2023-10-23 18:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0003_itemrewiew'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemRewiew',
            new_name='ItemReview',
        ),
    ]
