# Generated by Django 4.2.5 on 2023-12-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_item_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='availability',
            field=models.BooleanField(default=False),
        ),
    ]
