# Generated by Django 4.2.5 on 2023-10-23 22:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0005_rename_itemreview_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Comments',
        ),
    ]
