# Generated by Django 4.2.5 on 2023-10-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='advantages',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='disadvantages',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
