# Generated by Django 4.2.5 on 2023-10-25 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_alter_comments_comment_alter_comments_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-comment_date',), 'verbose_name_plural': 'Comments'},
        ),
    ]
