# Generated by Django 4.2.5 on 2023-10-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_remove_comments_item_remove_item_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ManyToManyField(related_name='brands', to='item.category')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
