# Generated by Django 4.2.5 on 2023-10-25 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0017_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
