# Generated by Django 4.2.5 on 2023-10-26 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_shoppingcartitem_item_and_more'),
        ('item', '0022_remove_brand_category_brand_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
