# Generated by Django 4.2.5 on 2023-10-26 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0023_remove_item_brand_remove_brand_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_brands', to='item.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_brands', to='item.category')),
            ],
            options={
                'unique_together': {('category', 'brand')},
            },
        ),
    ]
