# Generated by Django 4.2.5 on 2023-10-26 09:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0025_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('comment', models.TextField()),
                ('advantages', models.CharField(blank=True, max_length=255, null=True)),
                ('disadvantages', models.CharField(blank=True, max_length=255, null=True)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='item.item')),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'ordering': ('-comment_date',),
            },
        ),
    ]
