# Generated by Django 4.2.5 on 2023-10-29 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0028_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
