# Generated by Django 4.2.5 on 2023-10-29 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0030_favoritecompare'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritecompare',
            name='compare_items',
            field=models.ManyToManyField(related_name='compares', to='item.item'),
        ),
        migrations.AlterField(
            model_name='favoritecompare',
            name='favorite_items',
            field=models.ManyToManyField(related_name='favorites', to='item.item'),
        ),
        migrations.AlterField(
            model_name='favoritecompare',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_compares', to=settings.AUTH_USER_MODEL),
        ),
    ]
