# Generated by Django 4.2.5 on 2023-11-08 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_remove_shoppingcartitem_item_and_more'),
        ('item', '0031_favoritecompare_compare_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritecompare',
            name='compare_items',
        ),
        migrations.RemoveField(
            model_name='favoritecompare',
            name='favorite_items',
        ),
        migrations.RemoveField(
            model_name='favoritecompare',
            name='user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category_brand',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='FavoriteCompare',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
