# Generated by Django 4.2.5 on 2023-11-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_remove_shoppingcartitem_item_and_more'),
        ('conversation', '0003_remove_conversationmessage_conversation_and_more'),
        ('item', '0037_favoritecompare_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritecompare',
            name='compare_items',
        ),
        migrations.RemoveField(
            model_name='favoritecompare',
            name='favorite_items',
        ),
        migrations.RemoveField(
            model_name='favoritecompare',
            name='user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category_brand',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='FavoriteCompare',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
