# Generated by Django 4.2.5 on 2023-11-09 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0040_favoritecompare_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritecompare',
            name='compare_items',
        ),
        migrations.RemoveField(
            model_name='favoritecompare',
            name='favorite_items',
        ),
        migrations.RemoveField(
            model_name='favoritecompare',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='FavoriteCompare',
        ),
    ]
