# Generated by Django 4.2.5 on 2023-11-09 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_remove_shoppingcartitem_item_and_more'),
        ('item', '0041_remove_favoritecompare_compare_items_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
