# Generated by Django 4.2.5 on 2023-11-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0044_favoritecompare_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
