# Generated by Django 4.2.5 on 2023-10-07 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('order_date',)},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('item_price',)},
        ),
    ]
