# Generated by Django 4.2.5 on 2023-12-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_conversationmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConversationMessage',
        ),
    ]
