# Generated by Django 4.2.5 on 2023-11-15 16:43

import conversation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0008_conversationmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationmessage',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='created_at',
            field=models.DateTimeField(default=conversation.models.current_time),
        ),
    ]
