# Generated by Django 4.2.5 on 2023-10-07 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcartitem',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='shoppingcartitem',
            old_name='user_id',
            new_name='user',
        ),
    ]
