# Generated by Django 4.2.5 on 2023-10-09 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_item_id_shoppingcartitem_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_id',
            new_name='order',
        ),
    ]
