# Generated by Django 4.2.5 on 2023-12-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
