# Generated by Django 4.2.5 on 2023-10-09 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_user_id_order_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='total_price',
        ),
    ]
