# Generated by Django 4.2.5 on 2023-10-11 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.contactinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.shippingaddress'),
            preserve_default=False,
        ),
    ]
