# Generated by Django 4.2.5 on 2023-10-12 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_contact_info_order_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
