# Generated by Django 4.2.5 on 2023-10-27 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_shoppingcartitem_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-order_date',)},
        ),
    ]
