# Generated by Django 4.2.5 on 2023-10-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='item',
            new_name='items',
        ),
    ]
