# Generated by Django 4.2.5 on 2023-10-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_rename_item_favorite_items'),
    ]

    database_operations = [migrations.AlterModelTable('Favorite', 'item')]

    state_operations = [migrations.DeleteModel('Favorite')]

    operations = [
      migrations.SeparateDatabaseAndState(
        database_operations=database_operations,
        state_operations=state_operations)
    ]
