# Generated by Django 4.2.5 on 2023-10-12 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='amount',
        ),
    ]
