# Generated by Django 4.2.5 on 2023-10-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_orderstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name_plural': 'Order Statuses'},
        ),
        migrations.RenameField(
            model_name='orderstatus',
            old_name='name',
            new_name='status',
        ),
    ]
