# Generated by Django 4.2.5 on 2023-10-14 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_rename_quantity_orderitem_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'ordering': ('user',)},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'ordering': ('user',), 'verbose_name_plural': 'Shipping addresses'},
        ),
    ]
