# Generated by Django 4.2.5 on 2023-10-31 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_paymentmethod_alter_orderstatus_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
