# Generated by Django 4.2.5 on 2023-11-09 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_shoppingcartitem_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingCartItem',
        ),
    ]
