# Generated by Django 4.2.5 on 2023-11-17 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_shoppingcartitem_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='ShoppingCartItem',
        ),
    ]
